### PR TITLE
PRed my :fire: mixtape fam

### PR DESCRIPTION
**Pull request by blha303**
This 🌮is so spicy you'll need a 🚒all up in your 👂holes

### CODE REVIEW

**Comment by md678685** [comment]
[Partial implementation of additional tape](https://md678685.keybase.pub/things/gobble.wav) @blha303

**Comment by SupaHam** [comment]
[PLEASE EVACUATE THE SITE!](https://www.youtube.com/watch?v=BQI1Fvp6rBw)

**Comment by md678685** [comment]
[Added fire alarms](https://md678685.keybase.pub/things/gobble2.wav) so people know how 🔥 this is

**Comment by md678685** [comment]
[Accidental syncopation](https://md678685.keybase.pub/things/gobble3.wav) because why not
```
🔥🔥🔥🔥
🔥 🚨 🔥
🔥 🚒 🔥
🔥🔥 🔥🔥
```

**Comment by LaxWasHere** [comment]
[It's time for a reeeeeemix](https://laxwashere.keybase.pub/gobble_remixdown.mp3)

**Comment by SupaHam** [comment]
Unbelievably good. 5/5

**Comment by blha303** [comment]
@md678685 tape content enhanced

**Comment by SupaHam** [comment]
Sounds the same to me

**Comment by blha303** [comment]
It is the same, it just has more 📼

**Pull request merged**
